# Generated by Django 5.1.3 on 2024-11-19 13:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobs_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part time', 'Part time'), ('Contract', 'Contract')], default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
