# Generated by Django 5.1.3 on 2024-11-21 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileJobSeeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default=0, max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('qualification', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('country', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_job_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
