# Generated by Django 5.1.3 on 2024-11-21 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profilejobseeker'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilejobseeker',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilejobseeker',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
