# Generated by Django 5.1.3 on 2024-11-21 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_applications'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applications',
            unique_together={('user', 'job')},
        ),
    ]
