# Generated by Django 5.1.3 on 2024-11-21 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_applications_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
