# Generated by Django 5.1.3 on 2024-11-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_user_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
